---
- name: Install python dependencies for managing apt repositories
  apt: pkg=python-pycurl
  tags: [nginx, repo]
  sudo: true
  remote_user: "{{ service_user }}"

- name: Add nginx repository
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ precise nginx' state=present update_cache=yes
  sudo: true
  tags: [nginx, repo]
  remote_user: "{{ service_user }}"

- name: Install nginx
  sudo: true
  apt: pkg=nginx state=latest
  tags: [nginx, install]
  remote_user: "{{ service_user }}"

- name: Ensure nginx config directories exist
  file: path={{ item }} state=directory
  sudo: true
  with_items:
    - /etc/nginx
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled
  tags: [nginx]
  remote_user: "{{ service_user }}"

- name: Remove default nginx configs
  sudo: true
  file: path=/etc/nginx/sites-available/default state=absent
  with_items:
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/conf.d
  notify: restart nginx
  tags: [nginx, config]
  remote_user: "{{ service_user }}"
